### ISSUE TITLE
Цыфры вместо букв.

### ISSUE THREAD

**Issue by andreykp** [xguest/iso_9_js#1]
Текст:
`Сьогодні п'ятниця
Читачів
це` 
Транслитировался в следующую бяку:
`S`ogodn1` p'yatny`2ya
CHy`tach1`v.
2e`

---

upd: Нашел рабочую версию здесь: https://github.com/sgaluza/meteor-translit

**Comment by xguest** [comment]
Спасибо
При перекодировке в UTF-8 пропал символ $, поправил.
