### ISSUE TITLE
Can't get it work with Webpack

### ISSUE THREAD

**Issue by tommiv** [xguest/iso_9_js#2]
Я напишу, пожалуй, по-русски. Первая строчка в скрипте – хешбенг `#!/usr/bin/env node;`, поэтому его невозможно импортировать через Webpack + Babel:

```
ERROR in ./~/iso_9/translit.js
    Module parse failed: /node_modules/iso_9/translit.js Unexpected character '#' (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected character '#' (1:0)
```

Предполагается работа только из консоли?

**Comment by xguest** [comment]
Скрипт не имеет зависимостей.
Использую в Microsoft JScript 5.8.18205.
Спасибо.
