### ISSUE TITLE
Please publish "small fix" commit to npm

### ISSUE THREAD

**Issue by DimaDubyk** [xguest/iso_9_js#3]
this commit is not published to npm: https://github.com/xguest/iso_9_js/commit/5298b39fa2c031cd004e821a6ed12d0a939b02a1
project with iso_9 dependency fails with error
ERROR in ./node_modules/iso_9/translit.js
Module parse failed: ..\node_modules\iso_9\translit.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node;
| /* jshint -W100 */
| /**

**Comment by xguest** [comment]
Hi, DimaDubyk!
Thanks, this is the standard header of *nix systems, I'll fix it with the 
update, but this can not interfere with the analyzer's operation.

**Comment by DimaDubyk** [comment]
Thanks a lot for quick response, I will wait for updated npm package.
