### ISSUE TITLE
Issue with capitalization

### ISSUE THREAD

**Issue by ArmorDarks** [xguest/iso_9_js#4]
Characters which transliterate into two characters, like `Ю` producing the wrong capitalization in sentences.

Examples:

```js
translit('Его звали Юра' 5)
```

Expected:

```
Ego zvali Yura
```

Actual:

```
Ego zvali YUra
```

**Comment by xguest** [comment]
Доброго времени суток
Извините.
ISO 9: 1995 описывает транслитерацию кириллических букв. 
А регистр букв описывается правилами употребления прописных и строчных букв.
Посмотрите, как работают транслитераторы на сайтах паспортно-визовых отделов.
Спасибо, за проявленный интерес.
С наилучшими пожеланиями
